### ISSUE TITLE
some chinese translation

### ISSUE THREAD

**Issue by ghost** [den-ser/android_releases#1]
I feel so lucky to see someone continue to maintain this rom in the xda forum, thank you for your contribution.I found  two place didn't show in chinese, but I don't know how to compile a rom at all. can you solve some of the remaining translation problems ?

**Comment by ghost** [comment]
![screenshot_20180822-141816](https://user-images.githubusercontent.com/15317249/44446794-bae81d00-a618-11e8-83ae-5652894547b7.png)
![screenshot_20180822-141819](https://user-images.githubusercontent.com/15317249/44446813-c50a1b80-a618-11e8-8723-0e85d6f31a4e.png)

**Comment by DroidFreak32** [comment]
You can contribute translations in https://crowdin.com/project/lineageos
